site_name: Pyfaceimage
site_description: Documentation for the Pyfaceimage Python package
site_author: Haiyang Jin
theme:
  name: material  # Material design theme
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    # - navigation.expand
    # - toc.follow
    # - toc.integrate


nav:
  - Home: index.md
  - Installation: installation.md
  - Usage Guide: 
    - Section name:
      - Read images: readim.ipynb
  - API Reference: 
    - all: api/api.md
    - class: api/class.md
    - function: api/function.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            docstring_style: numpy
  - mknotebooks
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/haiyangjin/pyfaceimage